name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Start JShell in background
        run: |
          jshell > /dev/null 2>&1 &
          sleep 5
        if: runner.os == 'Linux'

      - name: Start JShell in background
        run: |
          start /b jshell > nul 2>&1
          timeout /t 5 > nul
        if: runner.os == 'Windows'

      - name: Run Go tests
        run: go test -v ./...
